# Generated by Django 4.2.15 on 2024-09-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodcat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandoption',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='bandoptionfeature',
            name='instruments',
        ),
        migrations.RemoveField(
            model_name='instrumentrental',
            name='rental_options',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='options',
        ),
        migrations.RemoveField(
            model_name='productcatalogue',
            name='category_links',
        ),
        migrations.AlterUniqueTogether(
            name='productcategorylink',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productcategorylink',
            name='catalogue',
        ),
        migrations.RemoveField(
            model_name='productcategorylink',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='BandOption',
        ),
        migrations.DeleteModel(
            name='BandOptionFeature',
        ),
        migrations.DeleteModel(
            name='InstrumentRental',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='LessonOption',
        ),
        migrations.DeleteModel(
            name='ProductCatalogue',
        ),
        migrations.DeleteModel(
            name='ProductCategoryLink',
        ),
        migrations.DeleteModel(
            name='RentalOption',
        ),
    ]
