# Generated by Django 4.2.15 on 2024-09-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodcat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandpackage',
            name='includes',
            field=models.CharField(choices=[('all', 'All Bands'), ('one', 'One Band Only')], default='all', help_text='Does this package include all or just one of the following bands?', max_length=5),
        ),
    ]
