# Generated by Django 4.2.15 on 2024-09-02 15:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prodcat', '0003_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandRelatedInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('instruments', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prodcat.instrument')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_instruments', to='prodcat.band')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
