# Generated by Django 4.2.15 on 2024-09-02 15:32

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prodcat', '0004_bandrelatedinstrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fullprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('under30price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('siblingprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BandPackageRelatedBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('bands', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prodcat.instrument')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_bands', to='prodcat.bandpackage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
