# Generated by Django 4.2.15 on 2024-09-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodcat', '0005_bandpackage_bandpackagerelatedband'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandpackagerelatedband',
            name='bands',
        ),
        migrations.RemoveField(
            model_name='bandrelatedinstrument',
            name='instruments',
        ),
        migrations.AddField(
            model_name='bandpackagerelatedband',
            name='bands',
            field=models.ManyToManyField(related_name='+', to='prodcat.band'),
        ),
        migrations.AddField(
            model_name='bandrelatedinstrument',
            name='instruments',
            field=models.ManyToManyField(related_name='+', to='prodcat.instrument'),
        ),
    ]
