# Generated by Django 4.2.15 on 2024-09-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodcat', '0006_remove_bandpackagerelatedband_bands_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandpackagerelatedband',
            name='bands',
        ),
        migrations.RemoveField(
            model_name='bandrelatedinstrument',
            name='instruments',
        ),
        migrations.AddField(
            model_name='bandpackagerelatedband',
            name='bands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prodcat.band'),
        ),
        migrations.AddField(
            model_name='bandrelatedinstrument',
            name='instruments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prodcat.instrument'),
        ),
    ]
