# Generated by Django 4.2.15 on 2024-08-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_paymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='cancel_url',
            field=models.URLField(blank=True, help_text='The URL to redirect to if the payment is canceled', null=True),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='success_url',
            field=models.URLField(blank=True, help_text='The URL to redirect to after a successful payment', null=True),
        ),
    ]
