# Generated by Django 4.2.15 on 2024-08-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_paymentsettings_cancel_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', help_text='The payment status of the enrolment', max_length=7),
        ),
    ]
