# Generated by Django 4.2.15 on 2024-08-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_enrolment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFERNOTSAY', 'Prefer Not Say')], default='OTHER', help_text="The member's sex at birth", max_length=12),
        ),
    ]
