# Generated by Django 4.2.15 on 2024-08-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_member_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ethnicity',
            field=models.CharField(choices=[('prefer_not_say', 'Prefer Not Say'), ('indian', 'Indian'), ('pakistani', 'Pakistani'), ('bangladeshi', 'Bangladeshi'), ('chinese', 'Chinese'), ('any_other_asian_background', 'Any other Asian background'), ('caribbean', 'Caribbean'), ('african', 'African'), ('any_other_black_black_british_or_caribbean_background', 'Any other Black, Black British, or Caribbean background'), ('white_and_black_caribbean', 'White and Black Caribbean'), ('white_and_black_african', 'White and Black African'), ('white_and_asian', 'White and Asian'), ('white_english_welsh_scottish_northern_irish_or_british', 'White - English, Welsh, Scottish, Northern Irish or British'), ('white_irish', 'White - Irish'), ('white_gypsy_or_irish_traveller', 'White - Gypsy or Irish Traveller'), ('white_roma', 'White - Roma'), ('any_other_white_background', 'Any other White background'), ('arab', 'Arab'), ('any_other_ethnic_group', 'Any other ethnic group')], default='Prefer Not Say', help_text="The member's ethnicity", max_length=54),
        ),
    ]
