# Generated by Django 4.2.15 on 2024-08-30 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('frontend', '0007_member_ethnicity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolmentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Enrolment Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MemberProfilePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Profile Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SignInPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'SignIn Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SignOutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'SignOut Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='signuppage',
            name='logo',
        ),
    ]
