# Generated by Django 4.2.15 on 2024-08-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_elcbhomepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='siblings',
            field=models.BooleanField(default=False),
        ),
    ]
