# Generated by Django 4.2.15 on 2024-09-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_member_siblings'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='bandDesc',
            field=models.CharField(blank=True, help_text='The description band package selected', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='bandPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='bands',
            field=models.CharField(blank=True, help_text='The code of the band package selected', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='lessons',
            field=models.CharField(blank=True, help_text='The code of the lesson package selected', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='lessonsDesc',
            field=models.CharField(blank=True, help_text='The description lesson package selected', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='lessonsPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='userType',
            field=models.CharField(blank=True, help_text='The rate applied', max_length=20, null=True),
        ),
    ]
