# Generated by Django 4.2.15 on 2024-09-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_enrolment_banddesc_enrolment_bandprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='stripeRef',
            field=models.CharField(blank=True, help_text='The stripeRef', max_length=50, null=True),
        ),
    ]
