# Generated by Django 4.2.15 on 2024-09-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_enrolment_striperef'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, help_text='Your Stripe WebHook Secret', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='stripe_id',
            field=models.CharField(blank=True, help_text='Your Stripe ID', max_length=255, null=True),
        ),
    ]
